import {
  ArrowLeftRight,
  Award,
  Bell,
  Compass,
  CreditCard,
  Crown,
  Gamepad2,
  HeartHandshake,
  Gavel,
  KeyRound,
  LayoutGrid,
  Link2,
  type LucideIcon,
  MessageSquare,
  QrCode,
  ScanLine,
  ShieldCheck,
  Smartphone,
  Sprout,
  Target,
  TriangleAlert,
  Wallet,
} from "lucide-react";

/** Nama ikon disimpan di JSON, bukan komponen — supaya konten tetap data. */
const PETA: Record<string, LucideIcon> = {
  kartu: CreditCard,
  perisai: ShieldCheck,
  kunci: KeyRound,
  waspada: TriangleAlert,
  qr: QrCode,
  pindai: ScanLine,
  transfer: ArrowLeftRight,
  dompet: Wallet,
  ponsel: Smartphone,
  tautan: Link2,
  peka: HeartHandshake,
  lonceng: Bell,
  tunas: Sprout,
  target: Target,
  mahkota: Crown,
  kompas: Compass,
  piala: Award,
  simulasi: Gamepad2,
  adukan: Gavel,
  feedback: MessageSquare,
};

export const ambilIkon = (nama: string): LucideIcon => PETA[nama] ?? LayoutGrid;
